// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ext/types/net.proto

package net

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetInput struct {
	Uri                  string             `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Headers              []*GetInput_Header `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetInput) Reset()         { *m = GetInput{} }
func (m *GetInput) String() string { return proto.CompactTextString(m) }
func (*GetInput) ProtoMessage()    {}
func (*GetInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a2e3e6b7e224274, []int{0}
}

func (m *GetInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInput.Unmarshal(m, b)
}
func (m *GetInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInput.Marshal(b, m, deterministic)
}
func (m *GetInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInput.Merge(m, src)
}
func (m *GetInput) XXX_Size() int {
	return xxx_messageInfo_GetInput.Size(m)
}
func (m *GetInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetInput proto.InternalMessageInfo

func (m *GetInput) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *GetInput) GetHeaders() []*GetInput_Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

type GetInput_Header struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInput_Header) Reset()         { *m = GetInput_Header{} }
func (m *GetInput_Header) String() string { return proto.CompactTextString(m) }
func (*GetInput_Header) ProtoMessage()    {}
func (*GetInput_Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a2e3e6b7e224274, []int{0, 0}
}

func (m *GetInput_Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInput_Header.Unmarshal(m, b)
}
func (m *GetInput_Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInput_Header.Marshal(b, m, deterministic)
}
func (m *GetInput_Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInput_Header.Merge(m, src)
}
func (m *GetInput_Header) XXX_Size() int {
	return xxx_messageInfo_GetInput_Header.Size(m)
}
func (m *GetInput_Header) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInput_Header.DiscardUnknown(m)
}

var xxx_messageInfo_GetInput_Header proto.InternalMessageInfo

func (m *GetInput_Header) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetInput_Header) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetOutput struct {
	Uri                  string   `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Body                 []byte   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	StatusCode           int32    `protobuf:"varint,3,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Error                string   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOutput) Reset()         { *m = GetOutput{} }
func (m *GetOutput) String() string { return proto.CompactTextString(m) }
func (*GetOutput) ProtoMessage()    {}
func (*GetOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a2e3e6b7e224274, []int{1}
}

func (m *GetOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOutput.Unmarshal(m, b)
}
func (m *GetOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOutput.Marshal(b, m, deterministic)
}
func (m *GetOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOutput.Merge(m, src)
}
func (m *GetOutput) XXX_Size() int {
	return xxx_messageInfo_GetOutput.Size(m)
}
func (m *GetOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetOutput proto.InternalMessageInfo

func (m *GetOutput) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *GetOutput) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *GetOutput) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GetOutput) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*GetInput)(nil), "net.GetInput")
	proto.RegisterType((*GetInput_Header)(nil), "net.GetInput.Header")
	proto.RegisterType((*GetOutput)(nil), "net.GetOutput")
}

func init() { proto.RegisterFile("ext/types/net.proto", fileDescriptor_6a2e3e6b7e224274) }

var fileDescriptor_6a2e3e6b7e224274 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0xdd, 0xb6, 0xda, 0xf1, 0x03, 0x59, 0x7b, 0x08, 0x3d, 0x48, 0x28, 0x1e, 0x02, 0xc2,
	0x6e, 0x89, 0xff, 0x40, 0x0f, 0xd1, 0x8b, 0x42, 0x8e, 0xde, 0x36, 0x66, 0x48, 0x43, 0x9a, 0xdd,
	0xb0, 0x99, 0x2d, 0xe6, 0xe2, 0x6f, 0x97, 0x6c, 0x08, 0x58, 0xe8, 0x6d, 0xde, 0xdb, 0x7d, 0xf3,
	0xde, 0x3c, 0xb8, 0xc7, 0x1f, 0x92, 0xd4, 0xb7, 0xd8, 0x49, 0x8d, 0x24, 0x5a, 0x6b, 0xc8, 0x70,
	0xa6, 0x91, 0xb6, 0xbf, 0x70, 0x99, 0x22, 0xbd, 0xeb, 0xd6, 0x11, 0xbf, 0x03, 0xe6, 0x6c, 0x15,
	0x06, 0x51, 0x10, 0xaf, 0xb2, 0x61, 0xe4, 0x02, 0x2e, 0xf6, 0xa8, 0x0a, 0xb4, 0x5d, 0x38, 0x8b,
	0x58, 0x7c, 0x95, 0xac, 0xc5, 0xa0, 0x9f, 0x14, 0xe2, 0xcd, 0x3f, 0x66, 0xd3, 0xa7, 0xcd, 0x0e,
	0x96, 0x23, 0x35, 0xec, 0xaa, 0xb1, 0x9f, 0x76, 0xd5, 0xd8, 0xf3, 0x35, 0x2c, 0x8e, 0xea, 0xe0,
	0x30, 0x9c, 0x79, 0x6e, 0x04, 0xdb, 0x12, 0x56, 0x29, 0xd2, 0xa7, 0xa3, 0xf3, 0x01, 0x38, 0xcc,
	0x73, 0x53, 0xf4, 0x5e, 0x73, 0x9d, 0xf9, 0x99, 0x3f, 0x00, 0x74, 0xa4, 0xc8, 0x75, 0xaf, 0xa6,
	0xc0, 0x90, 0x45, 0x41, 0xbc, 0xc8, 0xfe, 0x31, 0x83, 0x11, 0x5a, 0x6b, 0x6c, 0x38, 0x1f, 0x8d,
	0x3c, 0x48, 0x9e, 0x80, 0x7d, 0x20, 0xf1, 0x47, 0x60, 0x29, 0x12, 0xbf, 0x39, 0xb9, 0x63, 0x73,
	0x3b, 0xc1, 0x31, 0xc8, 0x4b, 0xf2, 0xb5, 0x2b, 0x2b, 0xda, 0xbb, 0x5c, 0x7c, 0x9b, 0x46, 0xba,
	0xba, 0x55, 0xf6, 0x50, 0xa9, 0x06, 0x35, 0xc9, 0xd2, 0x9a, 0x46, 0x2b, 0xaa, 0x8e, 0x28, 0x4f,
	0x4a, 0xcd, 0x97, 0xbe, 0xd5, 0xe7, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x0e, 0xcb, 0xab,
	0x6c, 0x01, 0x00, 0x00,
}
